# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_ip.xci
# IP: The module: 'ila_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_ip.xci
# IP: The module: 'ila_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/RAM/RAM.srcs/sources_1/ip/ila_ip/ila_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
