# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led.xdc

# Block Designs: bd/test/test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_led_control_0_0/test_led_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_led_control_0_0 || ORIG_REF_NAME==test_led_control_0_0} -quiet] -quiet

# IP: bd/test/ip/test_xlconstant_0_0/test_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_xlconstant_0_0 || ORIG_REF_NAME==test_xlconstant_0_0} -quiet] -quiet

# XDC: bd/test/test_ooc.xdc
