# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_processing_system7_0_1/led_processing_system7_0_1.xci
# IP: The module: 'led_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_processing_system7_0_1/led_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_processing_system7_0_1/led_processing_system7_0_1.xci
# IP: The module: 'led_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_processing_system7_0_1/led_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
