# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi_output_test.xdc

# IP: ip/video_clock_2/video_clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_clock || ORIG_REF_NAME==video_clock} -quiet] -quiet
