# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/system_axi_smc_3.xci
# IP: The module: 'system_axi_smc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/bd_45a3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_0/bd_45a3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_1/bd_45a3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_2/bd_45a3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_3/bd_45a3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_4/bd_45a3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_5/bd_45a3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_6/bd_45a3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_7/bd_45a3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_8/bd_45a3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_9/bd_45a3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_1/bd_45a3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_1/bd_45a3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_5/bd_45a3_s00a2s_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_6/bd_45a3_sarn_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_7/bd_45a3_srn_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_8/bd_45a3_m00s2a_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/system_axi_smc_3.xci
# IP: The module: 'system_axi_smc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/bd_45a3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_0/bd_45a3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_1/bd_45a3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_2/bd_45a3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_3/bd_45a3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_4/bd_45a3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_5/bd_45a3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_6/bd_45a3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_7/bd_45a3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_8/bd_45a3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_9/bd_45a3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_1/bd_45a3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_1/bd_45a3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_5/bd_45a3_s00a2s_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_6/bd_45a3_sarn_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_7/bd_45a3_srn_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/bd_0/ip/ip_8/bd_45a3_m00s2a_0_ooc.xdc

# XDC: d:/MyWorkSpace/ZYNQ/ARM/VDMA_HDMI/VDMA_HDMI.srcs/sources_1/bd/system/ip/system_axi_smc_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
