# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.srcs/sources_1/bd/i_stream2filter/ip/i_stream2filter_c_shift_ram_0_4/i_stream2filter_c_shift_ram_0_4.xci
# IP: The module: 'i_stream2filter_c_shift_ram_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.srcs/sources_1/bd/i_stream2filter/ip/i_stream2filter_c_shift_ram_0_4/i_stream2filter_c_shift_ram_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'i_stream2filter_c_shift_ram_0_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.srcs/sources_1/bd/i_stream2filter/ip/i_stream2filter_c_shift_ram_0_4/i_stream2filter_c_shift_ram_0_4.xci
# IP: The module: 'i_stream2filter_c_shift_ram_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.srcs/sources_1/bd/i_stream2filter/ip/i_stream2filter_c_shift_ram_0_4/i_stream2filter_c_shift_ram_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'i_stream2filter_c_shift_ram_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
