# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0.xci
# IP: The module: 'led_rst_ps7_0_10M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_rst_ps7_0_10M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_rst_ps7_0_10M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_rst_ps7_0_10M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0.xci
# IP: The module: 'led_rst_ps7_0_10M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_rst_ps7_0_10M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_rst_ps7_0_10M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_state/HLS_LES_PWM/HLS_LES_PWM.srcs/sources_1/bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_rst_ps7_0_10M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
