# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PL_EMIO_KEY.xdc

# Block Designs: bd/zynq_embedded_system/zynq_embedded_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_embedded_system || ORIG_REF_NAME==zynq_embedded_system} -quiet] -quiet

# IP: bd/zynq_embedded_system/ip/zynq_embedded_system_processing_system7_0_0/zynq_embedded_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_embedded_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_embedded_system_processing_system7_0_0} -quiet] -quiet

# XDC: bd/zynq_embedded_system/zynq_embedded_system_ooc.xdc
