# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_state.xdc

# Block Designs: bd/led/led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led || ORIG_REF_NAME==led} -quiet] -quiet

# IP: bd/led/ip/led_processing_system7_0_1/led_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_processing_system7_0_1 || ORIG_REF_NAME==led_processing_system7_0_1} -quiet] -quiet

# IP: bd/led/ip/led_led_state_0_1/led_led_state_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_led_state_0_1 || ORIG_REF_NAME==led_led_state_0_1} -quiet] -quiet

# IP: bd/led/ip/led_auto_pc_1/led_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_auto_pc_1 || ORIG_REF_NAME==led_auto_pc_1} -quiet] -quiet

# IP: bd/led/ip/led_ps7_0_axi_periph_2/led_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ps7_0_axi_periph_2 || ORIG_REF_NAME==led_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/led/ip/led_rst_ps7_0_10M_0/led_rst_ps7_0_10M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_rst_ps7_0_10M_0 || ORIG_REF_NAME==led_rst_ps7_0_10M_0} -quiet] -quiet

# XDC: bd/led/led_ooc.xdc
