# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyWorkSpace/ZYNQ/HLS/led_control/HLS_LED/HLS_LED.srcs/sources_1/bd/test/ip/test_led_control_0_0/test_led_control_0_0.xci
# IP: The module: 'test_led_control_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_control/HLS_LED/HLS_LED.srcs/sources_1/bd/test/ip/test_led_control_0_0/constraints/led_control_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_led_control_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MyWorkSpace/ZYNQ/HLS/led_control/HLS_LED/HLS_LED.srcs/sources_1/bd/test/ip/test_led_control_0_0/test_led_control_0_0.xci
# IP: The module: 'test_led_control_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/HLS/led_control/HLS_LED/HLS_LED.srcs/sources_1/bd/test/ip/test_led_control_0_0/constraints/led_control_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_led_control_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
