set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN J16 [get_ports o_led]
set_property PACKAGE_PIN R17 [get_ports i_key]
set_property PACKAGE_PIN N15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports i_key]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]

set_property PACKAGE_PIN J16 [get_ports {o_led[0]}]
set_property PACKAGE_PIN K16 [get_ports {o_led[1]}]
set_property PACKAGE_PIN M15 [get_ports {o_led[2]}]
set_property PACKAGE_PIN M14 [get_ports {o_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_key_1]
set_property IOSTANDARD LVCMOS33 [get_ports i_key_2]
set_property PACKAGE_PIN T17 [get_ports i_key_1]
set_property PACKAGE_PIN R17 [get_ports i_key_2]
