webtalk_init -webtalk_dir D:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.sim/sim_1/behav/xsim/xsim.dir/tb_median_filter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 16 22:14:44 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211908313_0_0_429" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c6cdbece-67d9-44cd-8e77-665288806287" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e8e73e83f6e04528aec6dd74b3ea0ec3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "38" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1920047 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "10.75_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14044_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3434967977 -regid "211908313_0_0_429" -xml D:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.sim/sim_1/behav/xsim/xsim.dir/tb_median_filter_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.sim/sim_1/behav/xsim/xsim.dir/tb_median_filter_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MyWorkSpace/ZYNQ/FPGA/median_filter/median_filter.sim/sim_1/behav/xsim/xsim.dir/tb_median_filter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
