# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyWorkSpace/ZYNQ/ARM/EMIO_LED/EMIO_LED.srcs/sources_1/bd/zynq_embedded_system/ip/zynq_embedded_system_processing_system7_0_0/zynq_embedded_system_processing_system7_0_0.xci
# IP: The module: 'zynq_embedded_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/EMIO_LED/EMIO_LED.srcs/sources_1/bd/zynq_embedded_system/ip/zynq_embedded_system_processing_system7_0_0/zynq_embedded_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_embedded_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MyWorkSpace/ZYNQ/ARM/EMIO_LED/EMIO_LED.srcs/sources_1/bd/zynq_embedded_system/ip/zynq_embedded_system_processing_system7_0_0/zynq_embedded_system_processing_system7_0_0.xci
# IP: The module: 'zynq_embedded_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyWorkSpace/ZYNQ/ARM/EMIO_LED/EMIO_LED.srcs/sources_1/bd/zynq_embedded_system/ip/zynq_embedded_system_processing_system7_0_0/zynq_embedded_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_embedded_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
